VALID_LABELS = [
    "INJURY_ROSTER",
    "TRANSACTION_CONTRACT",
    "MATCH_RELATED",
    "PERFORMANCE_ANALYSIS",
    "INTERVIEW",
    "PLAYER_RELATED",
    "CLUB_OPERATION",
    "ETC",
]

VALID_LABEL_SET = set(VALID_LABELS)
