export const FAN_VOICE_LIMITS = {
  MAX_VISIBLE_BUBBLES: 12,
  DESKTOP_LANES: 5,
  TABLET_LANES: 4,
  MOBILE_LANES: 3,
  LANE_HEIGHT_PX: 42,
  LANE_GAP_PX: 8,
  MIN_SPAWN_GAP_MS: 900,
} as const

export const FAN_VOICE_ANIMATION = {
  MIN_DURATION_SEC: 10,
  MAX_DURATION_SEC: 18,
  PER_CHAR_SEC: 0.12,
} as const

export const FAN_VOICE_POLLING = {
  DEFAULT_INTERVAL_MS: 5000,
  SLOW_MODE_INTERVAL_MS: 8000,
  ERROR_RETRY_MS: 10000,
} as const
